# Site settings
title: CARL WINE & SPIRITS
email: bjorn.nyqvist@carlwine.se
description: > # this means to ignore newlines until "baseurl:"
  Carl Wine & Spirits är specialister på den nordiska marknaden.
baseurl: "/carlwine.se" # the subpath of your site, e.g. /blog/
url: "http://calvinmcgee.github.io" # the base hostname & protocol for your site

destination: _site_dev

exclude:
  - Gemfile
  - Gemfile.lock
  - wercker.yml

# Build settings
markdown: kramdown

permalink: pretty

gems:
  - jekyll-assets
  - jekyll-sitemap

assets:
  compress:
    css: false
    javascript: false
  prefix: "/assets"
  digest: false
  sources:
    - _assets/sass
    - _assets/js

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
