# Site settings
title: CARL WINE & SPIRITS
email: bjorn.nyqvist@carlwine.se
description: > # this means to ignore newlines until "baseurl:"
  Carl Wine & Spirits är specialister på den nordiska marknaden.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://carlwine.se" # the base hostname & protocol for your site

destination: _site

exclude:
  - Gemfile
  - Gemfile.lock
  - wercker.yml

# Build settings
markdown: kramdown

permalink: pretty

gems:
  - jekyll-assets
  - jekyll-sitemap

assets:
  compress:
    css: true
  prefix: "/assets"
  digest: true
  sources:
    - _assets/sass

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
