# Site settings
title: Carl Vine & Wine
email: bjorn.nyqvist@carlwine.se
description: > # this means to ignore newlines until "baseurl:"
  Carl Wine & Spirits are specialists in the Nordic market.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://carlwine.se" # the base hostname & protocol for your site

destination: _site

exclude:
  - Gemfile
  - Gemfile.lock
  - wercker.yml

# Build settings
markdown: kramdown

permalink: pretty

gems:
  - jekyll-assets
  - jekyll-sitemap

assets:
  compress:
    css: true
    javascript: true
  prefix: "/assets"
  digest: true
  sources:
    - _assets/sass
    - _assets/js

language: "en"

defaults:
  -
    scope:
      path: "producers"
    values:
      layout: "subpage"
  -
    scope:
      path: ""
    values:
      layout: "page"
